#!/bin/bash
# ================================================================
# ProofGraph — Quick .env setup
# Run: bash setup_env.sh
# ================================================================

ENV_FILE="$(dirname "$0")/backend/.env"

echo ""
echo "⬡ ProofGraph — Backend Configuration"
echo "======================================="
echo ""
echo "Your OG faucet wallet private key is needed for:"
echo "  ✓ Live TEE inference on OpenGradient"
echo "  ✓ On-chain tx hash proofs (verified nodes)"
echo "  ✓ x402 micropayments to Digital Twins"
echo "  ✓ MemSync verifiable memory"
echo ""
echo "Get $OPG tokens: https://faucet.opengradient.ai"
echo ""

read -p "Paste your wallet private key (0x...): " PK
if [[ -z "$PK" ]]; then echo "Skipped."; exit 0; fi

read -p "OG email (optional, press Enter to skip): " EMAIL
read -p "OG password (optional, press Enter to skip): " PASS

cat > "$ENV_FILE" << ENVEOF
# ProofGraph — Generated by setup_env.sh
OG_PRIVATE_KEY=${PK}
OG_EMAIL=${EMAIL}
OG_PASSWORD=${PASS}
MEMSYNC_API_KEY=
APP_HOST=0.0.0.0
APP_PORT=8000
DATABASE_PATH=./proofgraph.db
ENVEOF

echo ""
echo "✅  backend/.env created!"
echo "   Restart the backend: cd backend && python main.py"
echo ""
